apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-vre-home.fullname" . }}
  labels:
    {{- include "frontend-vre-home.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: {{ include "frontend-vre-home.fullname" . }}
  selector:
    {{- include "frontend-vre-home.selectorLabels" . | nindent 4 }}
